function envelope_features = build_features_set(data, env_data, TM_1_data,TM_2_data, fc)

% Initialize a cell array to store rows of the feature table
features_rows = [];

% Loop through each map type: MAP_A, MAP_B, MAP_C
for i = ["A", "B", "C"]
    map = 'MAP_' + i;
    subjects = fieldnames(data.(map));

    % Loop through each subject
    for j = 1:length(subjects)
        sub = subjects{j};

        % Get the number of signals for the current subject
        [~, N] = size(data.(map).(sub).rov_trace);

        sub_num=split(sub,'_');
        sub_num=split(sub_num{2},i);
        sub_num=sub_num{end};
        for h = 1:N
            % Extract the rov_trace signal and its corresponding envelope
            example_rov = data.(map).(sub).rov_trace{:,h};
            example_env = env_data.(map).(sub).rov_trace{:,h};
            example_corr_TM_1=TM_1_data.(map).(sub).rov_trace{:,h};
            example_corr_TM_2=TM_2_data.(map).(sub).rov_trace{:,h};
            T=TM_1_data.T;

            disp([sub+"-"+num2str(h)])

            %% Computing features
            %% Envelope
            % disp([sub+"-"+num2str(h)])
            [active_areas_number,...
                Dominant_peak, Dominant_peak_time, Subdominant_peak, Subdominant_peak_time, Minor_peak, Minor_peak_time, ...
                Dominant_peak_env, Dominant_peak_env_time, Subdominant_peak_env, Subdominant_peak_env_time, Minor_peak_env, Minor_peak_env_time, ...
                First_peak, First_peak_time, Second_peak, Second_peak_time, Third_peak, Third_peak_time,...
                First_peak_env, First_peak_env_time, Second_peak_env, Second__peak_env_time, Third_peak_env, Third_peak_env_time,...
                duration,silent_phase,...
                silent_rateo,atrial_ventricular_ratio,atrial_ventricular_time_ratio,minor_to_major_ratio,minor_to_subdominant_ratio,n_active_areas_on_duration_ratio] = compute_envelope_features(example_env, example_rov, fc);

            %% Template matching
            record_id=[i,sub_num,h];
            [cross_peak_1,cross_peak_pos_1,corr_energy_1,...
                cross_peak_2,cross_peak_pos_2,corr_energy_2]=compute_TM_features(record_id,data, env_data,example_corr_TM_1,example_corr_TM_2,T, fc);

            %% Other features
            % ApEN=ApEn(example_rov,3,0.38*std(example_rov,[],"omitnan")); % Doque et al.
            % Fragmentation=compute_fragmentation_value(example_rov,0.750,fc); % Baldazzi et al.
            % App=compute_pp_amplitude(example_rov,fc); % Baldazzi et al.

            [Major_ALFP,Major_AMFP,Major_AHFP,...
                Medium_ALFP,Medium_AMFP,Medium_AHFP,...
                Lowest_ALFP,Lowest_AMFP,Lowest_AHFP,...
                First_ALFP, First_AMFP,First_AHFP, ...
                Second_ALFP, Second_AMFP, Second_AHFP, ...
                Third_ALFP, Third_AMFP, Third_AHFP]=compute_STFT_features(example_rov,example_env,fc);
            % % Save the computed features as strings (to handle NaN values)
            % feature_row = {
            %     string(sub_num),...
            %     string(n_peaks), string(env_peak1_time), string(env_peak2_time), string(env_peak3_time), ...
            %     string(env_peak1_val), string(env_peak2_val), string(env_peak3_val),...
            %     string(peak1_time), string(peak2_time), string(peak3_time), ...
            %     string(peak1_val), string(peak2_val), string(peak3_val), ...
            %     string(duration), string(silent_phase), string(silent_rateo), ...
            %     string(atrial_ventricular_ratio),string(atrial_ventricular_time_ratio),...
            %     string(third_major_ratio),string(third_second_ratio), string(n_peaks_duration_ratio), ...
            %     string(cross_peak_1),string(cross_peak_pos_1),string(corr_energy_1),...
            %     string(cross_peak_2),string(cross_peak_pos_2),string(corr_energy_2),...
            %     string(ApEN),...
            %     string(Fragmentation),...
            %     string(App),...
            %     string(Pr20),string(Pr40),string(Pr60),string(Pr80),string(Pr100),string(Pr120),string(Pr140),string(Pr160),string(Pr180),string(Pr200),...
            %     string(Pr220),string(Pr240),string(Pr260),string(Pr280),string(Pr300),string(Pr320),...
            %     string(mnf),string(pkf),string(mnp),string(psr),...
            %     map % Add the "class" column with the map identifier
            %     };
            % Save the computed features as strings (to handle NaN values)
            feature_row = {
                string(sub_num),string(active_areas_number), string(Dominant_peak), string(Dominant_peak_time), string(Subdominant_peak), string(Subdominant_peak_time), string(Minor_peak), string(Minor_peak_time),...
                string(Dominant_peak_env), string(Dominant_peak_env_time), string(Subdominant_peak_env), string(Subdominant_peak_env_time), string(Minor_peak_env), string(Minor_peak_env_time),...
                string(First_peak), string(First_peak_time), string(Second_peak), string(Second_peak_time), string(Third_peak), string(Third_peak_time),...
                string(First_peak_env), string(First_peak_env_time), string(Second_peak_env), string(Second__peak_env_time), string(Third_peak_env), string(Third_peak_env_time),...
                string(duration), string(silent_phase),...
                string(silent_rateo), string(atrial_ventricular_ratio), string(atrial_ventricular_time_ratio), string(minor_to_major_ratio), string(minor_to_subdominant_ratio), string(n_active_areas_on_duration_ratio),...
                string(cross_peak_1), string(cross_peak_pos_1), string(corr_energy_1), ...
                string(cross_peak_2), string(cross_peak_pos_2), string(corr_energy_2),...
                string(Major_ALFP), string(Major_AMFP), string(Major_AHFP), ...
                string(Medium_ALFP), string(Medium_AMFP), string(Medium_AHFP), ...
                string(Lowest_ALFP), string(Lowest_AMFP), string(Lowest_AHFP),...
                string(First_ALFP), string(First_AMFP), string(First_AHFP), ...
                string(Second_ALFP), string(Second_AMFP), string(Second_AHFP), ...
                string(Third_ALFP), string(Third_AMFP), string(Third_AHFP),...
                map % Add the "class" column with the map identifier
                };

            % Append the current row to the dataset
            features_rows = [features_rows; feature_row];
        end
    end
end

% % Create the final table with column names
% envelope_features = cell2table(features_rows, ...
%     'VariableNames', {'id','N_peaks', 'env_peak1_time', 'env_peak2_time', 'env_peak3_time','env_peak1_val', 'env_peak2_val', 'env_peak3_val', ...
%     'peak1_time', 'peak2_time', 'peak3_time','peak1_val', 'peak2_val', 'peak3_val',...
%     'duration', 'silent_phase', ...
%     'silent_rateo', 'atrial_ventricular_ratio', 'atrial_ventricular_time_ratio',...
%     'third_major_ratio','third_second_ratio','n_peaks_duration_rateo',...
%     'cross_peak_1','cross_peak_time_1','cross_energy_1',...
%     'cross_peak_2','cross_peak_time_2','cross_energy_2',...
%     'ApEN',...
%     'Fragmentation',...
%     'App',...
%     'Pr20', 'Pr40', 'Pr60', 'Pr80', 'Pr100', 'Pr120', 'Pr140', 'Pr160', 'Pr180', 'Pr200', ...
%     'Pr220', 'Pr240', 'Pr260', 'Pr280', 'Pr300', 'Pr320', ...
%     'mnf', 'pkf', 'mnp', 'psr',...
%     'class'});

% Create the final table with column names
envelope_features = cell2table(features_rows, ...
    'VariableNames', {'id','active_areas_number', 'Dominant_peak', 'Dominant_peak_time', 'Subdominant_peak', 'Subdominant_peak_time', 'Minor_peak', 'Minor_peak_time', ...
    'Dominant_peak_env', 'Dominant_peak_env_time', 'Subdominant_peak_env', 'Subdominant_peak_env_time', 'Minor_peak_env', 'Minor_peak_env_time',...
    'First_peak', 'First_peak_time', 'Second_peak', 'Second_peak_time', 'Third_peak', 'Third_peak_time',...
    'First_peak_env', 'First_peak_env_time', 'Second_peak_env', 'Second__peak_env_time', 'Third_peak_env', 'Third_peak_env_time',...
    'duration', 'silent_phase',...
    'silent_rateo', 'atrial_ventricular_ratio', 'atrial_ventricular_time_ratio', 'minor_to_major_ratio', 'minor_to_subdominant_ratio', 'n_active_areas_on_duration_ratio',...
    'cross_peak_1', 'cross_peak_time_1', 'cross_energy_1', ...
    'cross_peak_2', 'cross_peak_time_2', 'cross_energy_2', ...
    'Dominant_AvgPowLF', 'Dominant_AvgPowMF', 'Dominant_AvgPowHF', ...
    'Subdominant_AvgPowLF', 'Subdominant_AvgPowMF', 'Subdominant_AvgPowHF', ...
    'Minor_AvgPowLF', 'Minor_AvgPowMF', 'Minor_AvgPowHF',...
    'First_AvgPowLF', 'First_AvgPowMF', 'First_AvgPowHF', ...
    'Second_AvgPowLF', 'Second_AvgPowMF', 'Second_AvgPowHF', ...
    'Third_AvgPowLF', 'Third_AvgPowMF', 'Third_AvgPowHF',...
    'class'});
end
